export const projects = [
  {
    id: "numo-oracle-system",
    title: "NUMO Oracle System",
    description: "AI-powered data analytics platform for predictive business intelligence",
    image: "/images/projects/numo-oracle-system.png",
    category: "in-house",
    stage: "beta",
    tags: ["AI", "Data Analytics", "Business Intelligence", "Machine Learning", "Predictive Analytics"],
    demoUrl: "https://numo-oracle.vercel.app",
  },
  {
    id: "kraftwerked-website",
    title: "Kraftwerked Numerology",
    description: "Modern numerology platform combining ancient wisdom with AI technology",
    image: "/images/projects/kraftwerked-website.png",
    category: "client",
    stage: "deployed",
    tags: ["Web Development", "Numerology", "AI Integration", "Custom Design", "Interactive Tools"],
    demoUrl: "https://kraftwerked.vercel.app",
  },
  {
    id: "hodge-documentary-website",
    title: "The Hodge Documentary",
    description: "Official website for the award-winning documentary film",
    image: "/images/projects/hodge-documentary.png",
    category: "client",
    stage: "deployed",
    tags: ["Film", "Documentary", "Media", "Interactive", "Responsive Design"],
    demoUrl: "https://hodge-documentary.vercel.app",
  },
  // Temporarily remove the Lolita Wilson project
  // {
  //   id: "lolita-wilson-website",
  //   title: "LolitaWilson.com",
  //   description: "Artist portfolio website with custom web application and e-commerce integration",
  //   image: "/images/projects/lolita-wilson-website.png",
  //   category: "client",
  //   stage: "building",
  //   tags: ["Artist Portfolio", "E-commerce", "Web Application", "Custom Design", "Event Management"],
  //   demoUrl: "https://lolitawilson.vercel.app",
  // },
  {
    id: "ai-content-generator",
    title: "AI Content Generator",
    description: "Advanced AI-powered content creation platform for marketing teams",
    image: "/images/projects/ai-content-generator.png",
    category: "in-house",
    stage: "deployed",
    tags: ["AI", "Content Creation", "Marketing", "NLP", "Automation"],
  },
  {
    id: "virtual-event-platform",
    title: "Virtual Event Platform",
    description: "Comprehensive platform for hosting immersive virtual events and conferences",
    image: "/images/projects/virtual-event-platform.png",
    category: "in-house",
    stage: "deployed",
    tags: ["Virtual Events", "Live Streaming", "Networking", "Interactive", "Analytics"],
  },
  {
    id: "brand-identity-system",
    title: "Brand Identity System",
    description: "Complete brand identity system for a global technology company",
    image: "/images/projects/brand-identity-system.png",
    category: "client",
    stage: "deployed",
    tags: ["Branding", "Design System", "Logo Design", "Typography", "Color Theory"],
  },
  {
    id: "enterprise-project-management-system",
    title: "Enterprise Project Management System",
    description: "Comprehensive project management solution for large enterprises",
    image: "/images/projects/enterprise-project-management.png",
    category: "client",
    stage: "deployed",
    tags: ["Project Management", "Enterprise", "Workflow", "Collaboration", "Analytics"],
  },
  {
    id: "data-visualization-dashboard",
    title: "Data Visualization Dashboard",
    description: "Interactive dashboard for visualizing complex datasets and analytics",
    image: "/images/projects/data-visualization-dashboard.png",
    category: "in-house",
    stage: "beta",
    tags: ["Data Visualization", "Analytics", "Dashboard", "Interactive", "Real-time"],
  },
  {
    id: "e-commerce-platform",
    title: "E-commerce Platform",
    description: "Scalable e-commerce solution with advanced product management and analytics",
    image: "/images/projects/e-commerce-platform.png",
    category: "client",
    stage: "deployed",
    tags: ["E-commerce", "Online Store", "Payment Processing", "Inventory Management", "Analytics"],
  },
  {
    id: "prompt-engineering-toolkit",
    title: "Prompt Engineering Toolkit",
    description: "Comprehensive toolkit for developing and optimizing AI prompts",
    image: "/images/projects/prompt-engineering-toolkit.png",
    category: "in-house",
    stage: "beta",
    tags: ["AI", "Prompt Engineering", "NLP", "Optimization", "Developer Tools"],
  },
  {
    id: "digital-marketing-campaign",
    title: "Digital Marketing Campaign",
    description: "Integrated digital marketing campaign for a major product launch",
    image: "/images/projects/digital-marketing-campaign.png",
    category: "client",
    stage: "deployed",
    tags: ["Digital Marketing", "Campaign Management", "Social Media", "Analytics", "Content Strategy"],
  },
  {
    id: "cloud-infrastructure-solution",
    title: "Cloud Infrastructure Solution",
    description: "Scalable cloud infrastructure solution for enterprise applications",
    image: "/images/projects/cloud-infrastructure-solution.png",
    category: "client",
    stage: "deployed",
    tags: ["Cloud Computing", "Infrastructure", "DevOps", "Scalability", "Security"],
  },
  {
    id: "ai-research-platform",
    title: "AI Research Platform",
    description: "Collaborative platform for AI researchers to share and analyze findings",
    image: "/images/projects/ai-research-platform.png",
    category: "in-house",
    stage: "concept",
    tags: ["AI Research", "Collaboration", "Data Analysis", "Machine Learning", "Academic"],
  },
  {
    id: "smart-city-concept",
    title: "Smart City Concept",
    description: "Comprehensive smart city concept with integrated IoT and data analytics",
    image: "/images/projects/smart-city-concept.png",
    category: "in-house",
    stage: "concept",
    tags: ["Smart City", "IoT", "Urban Planning", "Sustainability", "Data Analytics"],
  },
  {
    id: "healthcare-app",
    title: "Healthcare App",
    description: "Mobile application for patient monitoring and healthcare management",
    image: "/images/projects/healthcare-app.png",
    category: "client",
    stage: "beta",
    tags: ["Healthcare", "Mobile App", "Patient Monitoring", "Telemedicine", "Data Security"],
  },
]

export const featuredProjects = [
  projects.find((p) => p.id === "kraftwerked-website")!,
  projects.find((p) => p.id === "numo-oracle-system")!,
  projects.find((p) => p.id === "hodge-documentary-website")!,
]
