export const projects = [
  {
    id: "enterprise-project-management-system",
    title: "Enterprise Project Management System",
    description:
      "A comprehensive project management platform for enterprise-level coordination and resource optimization.",
    image: "/images/projects/enterprise-project-management.png",
    category: "in-house",
    stage: "deployed",
    tags: ["Project Management", "Enterprise Software", "SaaS"],
  },
  {
    id: "ai-content-generator",
    title: "AI Content Generator",
    description: "An advanced tool that generates high-quality content for various marketing channels.",
    image: "/images/projects/ai-content-generator.png",
    category: "in-house",
    stage: "deployed",
    tags: ["AI", "Content Marketing", "SaaS"],
  },
  {
    id: "virtual-event-platform",
    title: "Virtual Event Platform",
    description: "A comprehensive platform for hosting engaging virtual events and conferences.",
    image: "/images/projects/virtual-event-platform.png",
    category: "client",
    stage: "deployed",
    tags: ["Web Development", "Real-time", "Events"],
  },
  {
    id: "brand-identity-system",
    title: "Brand Identity System",
    description: "A complete brand identity system for a tech startup in the healthcare space.",
    image: "/images/projects/brand-identity-system.png",
    category: "client",
    stage: "deployed",
    tags: ["Graphic Design", "Branding", "Healthcare"],
  },
  {
    id: "hodge-documentary-website",
    title: "The Hodge Documentary Website",
    description:
      "A comprehensive project including website development and a complete graphic design package featuring a custom logo design.",
    image: "/images/projects/hodge-documentary.png",
    category: "client",
    stage: "deployed",
    tags: ["Web Development", "Documentary", "Social Impact", "Graphic Design", "Logo Design"],
  },
  {
    id: "data-visualization-dashboard",
    title: "Data Visualization Dashboard",
    description: "An interactive dashboard for visualizing complex business data and analytics.",
    image: "/images/projects/data-visualization-dashboard.png",
    category: "client",
    stage: "beta",
    tags: ["Data Visualization", "Analytics", "UI/UX"],
  },
  {
    id: "e-commerce-platform",
    title: "E-Commerce Platform",
    description: "A scalable e-commerce platform with advanced product recommendation features.",
    image: "/images/projects/e-commerce-platform.png",
    category: "client",
    stage: "deployed",
    tags: ["E-Commerce", "Web Development", "AI"],
  },
  {
    id: "prompt-engineering-toolkit",
    title: "Prompt Engineering Toolkit",
    description: "A comprehensive toolkit for optimizing AI prompts across different models and use cases.",
    image: "/images/projects/prompt-engineering-toolkit.png",
    category: "in-house",
    stage: "beta",
    tags: ["AI", "Prompt Engineering", "Developer Tools"],
  },
  {
    id: "digital-marketing-campaign",
    title: "Digital Marketing Campaign",
    description: "A multi-channel digital marketing campaign for a consumer product launch.",
    image: "/images/projects/digital-marketing-campaign.png",
    category: "client",
    stage: "deployed",
    tags: ["Marketing", "Social Media", "Analytics"],
  },
  {
    id: "cloud-infrastructure-solution",
    title: "Cloud Infrastructure Solution",
    description: "A secure and scalable cloud infrastructure solution for a financial services company.",
    image: "/images/projects/cloud-infrastructure-solution.png",
    category: "client",
    stage: "deployed",
    tags: ["Cloud", "Security", "Infrastructure"],
  },
  {
    id: "ai-research-platform",
    title: "AI Research Platform",
    description: "A platform for conducting and sharing AI research and experiments.",
    image: "/images/projects/ai-research-platform.png",
    category: "in-house",
    stage: "building",
    tags: ["AI", "Research", "Collaboration"],
  },
  {
    id: "smart-city-concept",
    title: "Smart City Concept",
    description: "A conceptual design for smart city infrastructure and services.",
    image: "/images/projects/smart-city-concept.png",
    category: "in-house",
    stage: "concept",
    tags: ["IoT", "Urban Planning", "Sustainability"],
  },
  {
    id: "healthcare-app",
    title: "Healthcare Mobile App",
    description: "A mobile application for patient monitoring and healthcare management.",
    image: "/images/projects/healthcare-app.png",
    category: "client",
    stage: "beta",
    tags: ["Healthcare", "Mobile", "UX Design"],
  },
]

export const featuredProjects = [
  projects.find((p) => p.id === "enterprise-project-management-system")!,
  projects.find((p) => p.id === "ai-content-generator")!,
  projects.find((p) => p.id === "hodge-documentary-website")!,
]
